// Mock data for development / demo purposes
export const MOCK_USER = {
  id: 'user_001',
  username: 'AnonymousFalcon847',
  university: 'IIT Delhi',
  karma: 1247,
  joinedCommunities: ['comm_1', 'comm_2', 'comm_3'],
  createdAt: new Date('2025-09-01'),
};

export const MOCK_POSTS = [
  {
    id: 'post_1',
    userId: 'user_001',
    username: 'AnonymousFalcon847',
    university: 'IIT Delhi',
    communityId: 'comm_1',
    communityName: 'Confessions',
    text: 'Just realized the library has a secret floor that nobody talks about. Found it while looking for a charger at 3am. The vibes there are unreal.',
    image: null,
    likes: 234,
    likedBy: [],
    commentCount: 45,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'post_2',
    userId: 'user_002',
    username: 'ShadowPhoenix312',
    university: 'KL University',
    communityId: 'comm_2',
    communityName: 'Memes',
    text: 'When the professor says "this won\'t be on the exam" but it\'s literally the first question 💀',
    image: 'https://picsum.photos/400/300',
    likes: 567,
    likedBy: ['user_001'],
    commentCount: 89,
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: 'post_3',
    userId: 'user_003',
    username: 'PhantomWolf099',
    university: 'BITS Pilani',
    communityId: 'comm_3',
    communityName: 'Academics',
    text: 'Anyone else feel like the grading system needs a complete overhaul? We should be evaluated on understanding, not rote memorization. Hot take but I think open-book exams should be the standard.',
    image: null,
    likes: 123,
    likedBy: [],
    commentCount: 34,
    createdAt: new Date(Date.now() - 14400000),
  },
  {
    id: 'post_4',
    userId: 'user_004',
    username: 'MysticCobra455',
    university: 'IIT Bombay',
    communityId: 'comm_1',
    communityName: 'Confessions',
    text: 'I accidentally submitted my assignment to the wrong professor and got a better grade than my actual class 😭',
    image: null,
    likes: 891,
    likedBy: ['user_001'],
    commentCount: 156,
    createdAt: new Date(Date.now() - 28800000),
  },
  {
    id: 'post_5',
    userId: 'user_005',
    username: 'NeonTiger782',
    university: 'NIT Trichy',
    communityId: 'comm_4',
    communityName: 'Campus Life',
    text: 'The new cafeteria menu is actually fire. Whoever decided to add biryani on Thursdays deserves an award.',
    image: 'https://picsum.photos/400/250',
    likes: 345,
    likedBy: [],
    commentCount: 67,
    createdAt: new Date(Date.now() - 43200000),
  },
];

export const MOCK_COMMUNITIES = [
  {
    id: 'comm_1',
    name: 'Confessions',
    description: 'Spill the tea anonymously. No judgement zone.',
    memberCount: 12400,
    members: ['user_001'],
    icon: '🤫',
    color: '#FF4500',
  },
  {
    id: 'comm_2',
    name: 'Memes',
    description: 'The dankest campus memes you\'ll ever see.',
    memberCount: 23100,
    members: ['user_001'],
    icon: '😂',
    color: '#FFD600',
  },
  {
    id: 'comm_3',
    name: 'Academics',
    description: 'Study tips, course reviews, and exam prep.',
    memberCount: 8900,
    members: ['user_001'],
    icon: '📚',
    color: '#1A1AFF',
  },
  {
    id: 'comm_4',
    name: 'Campus Life',
    description: 'Everything about life on campus.',
    memberCount: 15600,
    members: [],
    icon: '🏫',
    color: '#00E676',
  },
  {
    id: 'comm_5',
    name: 'Placements',
    description: 'Job prep, interview tips, and placement updates.',
    memberCount: 19200,
    members: [],
    icon: '💼',
    color: '#FF4500',
  },
  {
    id: 'comm_6',
    name: 'Lost & Found',
    description: 'Lost something? Found something? Post here.',
    memberCount: 4300,
    members: [],
    icon: '🔍',
    color: '#9E9E9E',
  },
];

export const MOCK_COMMENTS = [
  {
    id: 'comment_1',
    postId: 'post_1',
    userId: 'user_002',
    username: 'ShadowPhoenix312',
    university: 'KL University',
    text: 'Wait WHAT? Which library? I need to find this place immediately.',
    parentId: null,
    createdAt: new Date(Date.now() - 3000000),
  },
  {
    id: 'comment_2',
    postId: 'post_1',
    userId: 'user_003',
    username: 'PhantomWolf099',
    university: 'BITS Pilani',
    text: 'Can confirm, the secret floor is real. Best study spot on campus.',
    parentId: null,
    createdAt: new Date(Date.now() - 2500000),
  },
  {
    id: 'comment_3',
    postId: 'post_1',
    userId: 'user_004',
    username: 'MysticCobra455',
    university: 'IIT Bombay',
    text: 'Bro you just exposed the best kept secret 💀',
    parentId: 'comment_1',
    createdAt: new Date(Date.now() - 2000000),
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif_1',
    userId: 'user_001',
    type: 'like',
    text: 'ShadowPhoenix312 liked your post',
    postId: 'post_1',
    read: false,
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    id: 'notif_2',
    userId: 'user_001',
    type: 'comment',
    text: 'PhantomWolf099 commented on your post',
    postId: 'post_1',
    read: false,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'notif_3',
    userId: 'user_001',
    type: 'reply',
    text: 'MysticCobra455 replied to your comment',
    postId: 'post_1',
    read: true,
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: 'notif_4',
    userId: 'user_001',
    type: 'like',
    text: 'NeonTiger782 liked your post',
    postId: 'post_4',
    read: true,
    createdAt: new Date(Date.now() - 14400000),
  },
];
